-- phpMyAdmin SQL Dump
-- version 3.4.5
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 12, 2012 at 02:43 AM
-- Server version: 5.5.16
-- PHP Version: 5.3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `alice`
--

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'this is converted in code to base 36 to get affiliate ids',
  `number` int(10) unsigned NOT NULL COMMENT 'phone number of user',
  `age` int(2) NOT NULL DEFAULT '0',
  `sex` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 unknown 1 male 2 female',
  `location` text,
  `ref_id` int(11) DEFAULT '0',
  `ads_recieved_week` int(11) NOT NULL DEFAULT '0' COMMENT 'tracked so that user is not spammed',
  `ads_recieved_total` int(11) NOT NULL DEFAULT '0' COMMENT 'total lifetime ads recieved',
  `total_profits_generated` int(11) NOT NULL DEFAULT '0' COMMENT 'lifetime profits generated by referals',
  `total_profits_generated_unrewarded` int(11) NOT NULL DEFAULT '0' COMMENT 'profits generated by refferals that user hasnt been compensated for',
  `join_confirmed` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `asl_requested` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `message_sent` text COMMENT 'hold text that user sent so human confirmation can be done on messages',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `number`, `age`, `sex`, `location`, `ref_id`, `ads_recieved_week`, `ads_recieved_total`, `total_profits_generated`, `total_profits_generated_unrewarded`, `join_confirmed`, `asl_requested`, `message_sent`) VALUES
(1, 4294967295, 22, 1, 'mombasa', 0, 2, 1, 11, 11, 0, 0, ''),
(2, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
